var a = document.getElementById("menu1");
var atx = a.getContext("2d");
atx.rect(1 , 5 , 250 , 40);
atx.strokeStyle = "#d3d3d3";
atx.stroke();
atx.fillStyle = "#d3d3d3";
atx.fill();
atx.font = "20px Tahoma";
atx.fillStyle = "#000000";
atx.fillText("Daily Movement: IN" , 10 , 32);

var b = document.getElementById("menu2");
var btx = b.getContext("2d");
btx.rect(1 , 5 , 250 , 40);
btx.strokeStyle = "#d3d3d3";
btx.stroke();
btx.fillStyle = "#d3d3d3";
btx.fill();
btx.font = "20px Tahoma";
btx.fillStyle = "#000000";
btx.fillText("Daily Movement: OUT" , 10 , 32);

var c = document.getElementById("menu3");
var ctx = c.getContext("2d");
ctx.rect(1 , 5 , 250 , 40);
ctx.strokeStyle = "#d3d3d3";
ctx.stroke();
ctx.fillStyle = "#d3d3d3";
ctx.fill();
ctx.font = "20px Tahoma";
ctx.fillStyle = "#000000";
ctx.fillText("Daily Stock" , 10 , 32);

var d = document.getElementById("menu4");
var dtx = d.getContext("2d");
dtx.rect(1 , 5 , 250 , 40);
dtx.strokeStyle = "#d3d3d3";
dtx.stroke();
dtx.fillStyle = "#d3d3d3";
dtx.fill();
dtx.font = "20px Tahoma";
dtx.fillStyle = "#000000";
dtx.fillText("Seal Collection" , 10 , 32);

var e = document.getElementById("menu5");
var etx = e.getContext("2d");
etx.rect(1 , 5 , 250 , 40);
etx.strokeStyle = "#d3d3d3";
etx.stroke();
etx.fillStyle = "#d3d3d3";
etx.fill();
etx.font = "20px Tahoma";
etx.fillStyle = "#000000";
etx.fillText("Container Log" , 10 , 32);
